// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofuxpfunfizyetpmggla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdXhwZnVuZml6eWV0cG1nZ2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTMxOTMsImV4cCI6MjA2NjE4OTE5M30.VAk_fZcvTOH-bnwsH18T3JGzDfXkwyglEBgTIf04ECU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);